---
version: "3.7"
services:

  gcse-web:
    image: x0rzkov/gcse:latest-alpine
    container_name: gcse-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    networks:
    - intranet
    - web
    volumes:
    - gcse-data:/opt/gcse/data
    command: ["web-server"]

  gcse-stored:
    container_name: gcse-stored
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8081:8081
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["stored"]

  gcse-countdocs:
    container_name: gcse-countdocs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["countdocs"]

  gcse-dump:
    container_name: gcse-dump
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["dump"]

  gcse-exps:
    container_name: gcse-exps
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["exps"]

  gcse-fillfound:
    container_name: gcse-fillfound
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["fillfound"]

  gcse-fixcrawldb:
    container_name: gcse-fixcrawldb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["fixcrawldb"]

  gcse-crawler:
    container_name: gcse-crawler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["crawler"]

  gcse-indexer:
    container_name: gcse-indexer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["indexer"]

  gcse-mergedocs:
    container_name: gcse-mergedocs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["mergedocs"]

  gcse-spider:
    container_name: gcse-spider
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["spider"]

  gcse-tocrawl:
    container_name: gcse-tocrawl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - gcse-data:/opt/gcse/data
    networks:
    - intranet
    command: ["tocrawl"]

volumes:
    gcse-data:

networks: 
  intranet:
  web:
    external: true  